fail_fast: true

default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: no-commit-to-branch
        name: 🚧 Protected Branches Checker
        args:
          - --branch=master
        pass_filenames: false
        stages:
          - pre-commit

      - id: check-added-large-files
        name: 📦 Large Files Checker
        args:
          - --maxkb=100
        stages:
          - pre-commit

      - id: check-case-conflict
        name: 🔠 Case Conflict Checker
        stages:
          - pre-commit

      - id: check-toml
        name: 📄 TOML Files Checker
        files: '.*\.toml'
        stages:
          - pre-commit

      - id: check-yaml
        name: 📄 YAML Files Checker
        files: '.*\.ya?ml'
        args:
          - --unsafe
        stages:
          - pre-commit

  - repo: https://github.com/gitleaks/gitleaks
    rev: 782f3104786efdce0f809bce8a9ff31f2fa1c9ed # v8.27.0
    hooks:
      - id: gitleaks
        name: 🔍 Secrets Checker
        entry: gitleaks detect --no-git --redact --verbose
        stages:
          - pre-commit

  - repo: https://github.com/commitizen-tools/commitizen
    rev: a0cc4901b0faaced74c713a9e355555fc4de0880 # v4.7.1
    hooks:
      - id: commitizen
        name: 📝 Standard Commit Message Checker
        stages:
          - commit-msg
