"""
Test Base36StringValueObject.
"""

from object_mother_pattern import StringMother
from pytest import mark, raises as assert_raises

from value_object_pattern.usables import Base36StringValueObject


@mark.unit_testing
def test_base36_string_value_object_happy_path() -> None:
    """
    Test Base36StringValueObject accepts a value generated by StringMother and the empty string.
    """
    value = StringMother.base36()

    assert Base36StringValueObject(value=value).value == value
    assert Base36StringValueObject(value='').value == ''


@mark.unit_testing
def test_base36_string_value_object_invalid_value() -> None:
    """
    Test Base36StringValueObject rejects characters outside the uppercase Base36 alphabet.
    """
    for value in ('abc', 'ABC-'):
        with assert_raises(
            expected_exception=ValueError,
            match=r'Base36StringValueObject value <<<.*>>> contains invalid Base36 characters.',
        ):
            Base36StringValueObject(value=value)


@mark.unit_testing
def test_base36_string_value_object_not_trimmed() -> None:
    """
    Test Base36StringValueObject rejects trailing whitespace through its trimmed string base.
    """
    with assert_raises(
        expected_exception=ValueError,
        match=r'.* value <<<.*>>> contains leading or trailing whitespaces. Only trimmed values are allowed.',
    ):
        Base36StringValueObject(value='ABC ')


@mark.unit_testing
def test_base36_string_value_object_invalid_type() -> None:
    """
    Test Base36StringValueObject rejects non-string values through its string base.
    """
    with assert_raises(
        expected_exception=TypeError,
        match=r'StringValueObject value <<<.*>>> must be a string. Got <<<.*>>> type.',
    ):
        Base36StringValueObject(value=StringMother.invalid_type())
