"""
Test HexadecimalStringValueObject and Base16StringValueObject.
"""

from object_mother_pattern import StringMother
from pytest import mark, raises as assert_raises

from value_object_pattern.usables import Base16StringValueObject, HexadecimalStringValueObject
from value_object_pattern.usables.primitives import (
    Base16StringValueObject as PrimitiveBase16StringValueObject,
    HexadecimalStringValueObject as PrimitiveHexadecimalStringValueObject,
)
from value_object_pattern.usables.primitives.string import (
    Base16StringValueObject as StringBase16StringValueObject,
    HexadecimalStringValueObject as StringHexadecimalStringValueObject,
    StringValueObject,
    TrimmedStringValueObject,
)


@mark.unit_testing
def test_hexadecimal_string_value_object_happy_path() -> None:
    """
    Test HexadecimalStringValueObject accepts a value generated by StringMother.
    """
    value = StringMother.hexadecimal()
    string_value = HexadecimalStringValueObject(value=value)

    assert type(string_value.value) is str
    assert string_value.value == value


@mark.unit_testing
def test_hexadecimal_string_value_object_case_and_empty_values() -> None:
    """
    Test HexadecimalStringValueObject accepts either letter case and the empty encoding.
    """
    assert HexadecimalStringValueObject(value='64e9740a').value == '64e9740a'
    assert HexadecimalStringValueObject(value='64E9740A').value == '64E9740A'
    assert HexadecimalStringValueObject(value='').value == ''


@mark.unit_testing
def test_hexadecimal_string_value_object_invalid_value() -> None:
    """
    Test HexadecimalStringValueObject rejects invalid Base16 values.
    """
    for value in ('F', '0xFF', 'GG', 'éé'):
        with assert_raises(
            expected_exception=ValueError,
            match=r'HexadecimalStringValueObject value <<<.*>>> must be valid Base16.',
        ):
            HexadecimalStringValueObject(value=value)


@mark.unit_testing
def test_hexadecimal_string_value_object_invalid_type() -> None:
    """
    Test HexadecimalStringValueObject rejects non-string values through its string base.
    """
    with assert_raises(
        expected_exception=TypeError,
        match=r'StringValueObject value <<<.*>>> must be a string. Got <<<.*>>> type.',
    ):
        HexadecimalStringValueObject(value=StringMother.invalid_type())


@mark.unit_testing
def test_base16_string_value_object_alias_exports_and_bases() -> None:
    """
    Test the Base16 alias, public exports, and inherited string contracts.
    """
    assert Base16StringValueObject is HexadecimalStringValueObject
    assert PrimitiveBase16StringValueObject is HexadecimalStringValueObject
    assert PrimitiveHexadecimalStringValueObject is HexadecimalStringValueObject
    assert StringBase16StringValueObject is HexadecimalStringValueObject
    assert StringHexadecimalStringValueObject is HexadecimalStringValueObject
    assert issubclass(HexadecimalStringValueObject, TrimmedStringValueObject)
    assert issubclass(HexadecimalStringValueObject, StringValueObject)
