"""
Test Base56StringValueObject.
"""

from object_mother_pattern import StringMother
from pytest import mark, raises as assert_raises

from value_object_pattern.usables import Base56StringValueObject


@mark.unit_testing
def test_base56_string_value_object_happy_path() -> None:
    """
    Test Base56StringValueObject accepts a value generated by StringMother and the empty string.
    """
    value = StringMother.base56()

    assert Base56StringValueObject(value=value).value == value
    assert Base56StringValueObject(value='').value == ''


@mark.unit_testing
def test_base56_string_value_object_invalid_value() -> None:
    """
    Test Base56StringValueObject rejects visually ambiguous characters.
    """
    for value in ('0', '1', 'I', 'O', 'l', 'o'):
        with assert_raises(
            expected_exception=ValueError,
            match=r'Base56StringValueObject value <<<.*>>> contains invalid Base56 characters.',
        ):
            Base56StringValueObject(value=value)


@mark.unit_testing
def test_base56_string_value_object_invalid_type() -> None:
    """
    Test Base56StringValueObject rejects non-string values through its string base.
    """
    with assert_raises(
        expected_exception=TypeError,
        match=r'StringValueObject value <<<.*>>> must be a string. Got <<<.*>>> type.',
    ):
        Base56StringValueObject(value=StringMother.invalid_type())
