"""
Test Base58StringValueObject.
"""

from object_mother_pattern import StringMother
from pytest import mark, raises as assert_raises

from value_object_pattern.usables import Base58StringValueObject


@mark.unit_testing
def test_base58_string_value_object_happy_path() -> None:
    """
    Test Base58StringValueObject accepts a value generated by StringMother and the empty string.
    """
    value = StringMother.base58()

    assert Base58StringValueObject(value=value).value == value
    assert Base58StringValueObject(value='').value == ''


@mark.unit_testing
def test_base58_string_value_object_invalid_value() -> None:
    """
    Test Base58StringValueObject rejects characters outside the Bitcoin alphabet.
    """
    for value in ('0', 'I', 'O', 'l'):
        with assert_raises(
            expected_exception=ValueError,
            match=r'Base58StringValueObject value <<<.*>>> contains invalid Base58 characters.',
        ):
            Base58StringValueObject(value=value)


@mark.unit_testing
def test_base58_string_value_object_invalid_type() -> None:
    """
    Test Base58StringValueObject rejects non-string values through its string base.
    """
    with assert_raises(
        expected_exception=TypeError,
        match=r'StringValueObject value <<<.*>>> must be a string. Got <<<.*>>> type.',
    ):
        Base58StringValueObject(value=StringMother.invalid_type())
