"""
Test Base32StringValueObject.
"""

from object_mother_pattern import StringMother
from pytest import mark, raises as assert_raises

from value_object_pattern.usables import Base32StringValueObject


@mark.unit_testing
def test_base32_string_value_object_happy_path() -> None:
    """
    Test Base32StringValueObject accepts a value generated by StringMother.
    """
    value = StringMother.base32()
    string_value = Base32StringValueObject(value=value)

    assert type(string_value.value) is str
    assert string_value.value == value


@mark.unit_testing
def test_base32_string_value_object_case_and_empty_values() -> None:
    """
    Test Base32StringValueObject accepts either letter case and the empty encoding.
    """
    assert Base32StringValueObject(value='MZXW6===').value == 'MZXW6==='
    assert Base32StringValueObject(value='mzxw6===').value == 'mzxw6==='
    assert Base32StringValueObject(value='').value == ''


@mark.unit_testing
def test_base32_string_value_object_invalid_value() -> None:
    """
    Test Base32StringValueObject rejects malformed values and invalid characters.
    """
    for value in ('MZXW6', 'MZXW6===!', 'MZXW6---', 'é======='):
        with assert_raises(
            expected_exception=ValueError,
            match=r'Base32StringValueObject value <<<.*>>> must be canonical padded Base32.',
        ):
            Base32StringValueObject(value=value)


@mark.unit_testing
def test_base32_string_value_object_non_canonical_value() -> None:
    """
    Test Base32StringValueObject rejects a decodable value with non-canonical padding bits.
    """
    with assert_raises(
        expected_exception=ValueError,
        match=r'Base32StringValueObject value <<<MZ======>>> must be canonical padded Base32.',
    ):
        Base32StringValueObject(value='MZ======')


@mark.unit_testing
def test_base32_string_value_object_invalid_type() -> None:
    """
    Test Base32StringValueObject rejects non-string values through its string base.
    """
    with assert_raises(
        expected_exception=TypeError,
        match=r'StringValueObject value <<<.*>>> must be a string. Got <<<.*>>> type.',
    ):
        Base32StringValueObject(value=StringMother.invalid_type())
