"""
Test Base64StringValueObject value object.
"""

from object_mother_pattern import StringMother
from pytest import mark, raises as assert_raises

from value_object_pattern.usables import Base64StringValueObject
from value_object_pattern.usables.primitives import Base64StringValueObject as PrimitiveBase64StringValueObject
from value_object_pattern.usables.primitives.string import (
    Base64StringValueObject as StringBase64StringValueObject,
    StringValueObject,
    TrimmedStringValueObject,
)


@mark.unit_testing
def test_base64_string_value_object_happy_path() -> None:
    """
    Test Base64StringValueObject accepts a value generated by StringMother.
    """
    value = StringMother.base64()
    string_value = Base64StringValueObject(value=value)

    assert type(string_value.value) is str
    assert string_value.value == value


@mark.unit_testing
def test_base64_string_value_object_canonical_values() -> None:
    """
    Test Base64StringValueObject accepts canonical padded and unpadded values.
    """
    for value in ('Zg==', 'Zm8=', 'Zm9v'):
        assert Base64StringValueObject(value=value).value == value


@mark.unit_testing
def test_base64_string_value_object_empty_value() -> None:
    """
    Test Base64StringValueObject accepts the Base64 encoding of empty bytes.
    """
    assert Base64StringValueObject(value='').value == ''


@mark.unit_testing
def test_base64_string_value_object_invalid_value() -> None:
    """
    Test Base64StringValueObject rejects invalid standard Base64 values.
    """
    for value in ('Zm9v!', 'Zg=', '-_8=', 'Zm 9v', 'é==='):
        with assert_raises(
            expected_exception=ValueError,
            match=r'Base64StringValueObject value <<<.*>>> must be canonical standard Base64.',
        ):
            Base64StringValueObject(value=value)


@mark.unit_testing
def test_base64_string_value_object_non_canonical_value() -> None:
    """
    Test Base64StringValueObject rejects a decodable value with non-canonical padding bits.
    """
    with assert_raises(
        expected_exception=ValueError,
        match=r'Base64StringValueObject value <<<ZE==>>> must be canonical standard Base64.',
    ):
        Base64StringValueObject(value='ZE==')


@mark.unit_testing
def test_base64_string_value_object_not_trimmed() -> None:
    """
    Test Base64StringValueObject rejects leading and trailing whitespace through its trimmed string base.
    """
    with assert_raises(
        expected_exception=ValueError,
        match=r'.* value <<<.*>>> contains leading or trailing whitespaces. Only trimmed values are allowed.',
    ):
        Base64StringValueObject(value=' Zm9v ')


@mark.unit_testing
def test_base64_string_value_object_invalid_type() -> None:
    """
    Test Base64StringValueObject rejects non-string values through its string base.
    """
    with assert_raises(
        expected_exception=TypeError,
        match=r'StringValueObject value <<<.*>>> must be a string. Got <<<.*>>> type.',
    ):
        Base64StringValueObject(value=StringMother.invalid_type())


@mark.unit_testing
def test_base64_string_value_object_public_exports_and_bases() -> None:
    """
    Test Base64StringValueObject is exported through each public usable layer and inherits both string contracts.
    """
    assert PrimitiveBase64StringValueObject is Base64StringValueObject
    assert StringBase64StringValueObject is Base64StringValueObject
    assert issubclass(Base64StringValueObject, TrimmedStringValueObject)
    assert issubclass(Base64StringValueObject, StringValueObject)
